# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a574ad316bc1fd1c481d01998626b6ea307196ce5440c710c0398495df3d72d15478608d843a878d1dd5a1b16c423daf2480d63be7ed1c7ad8a3a8452447a3ce

test:
  secret_key_base: 17af60826cb6fc3d472b75dc8bfce4eb201e1201e43bc3338f84d5171998e01b4aba3de833eaf37a84a02b543e1de28bfea1bc747a6ae7642f04f95904277036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
